gsoc:
    - '/gsoc|summer/i'
bug:
    - '/bug|not working|fail|fails|error/i'
new notebook:
    - '/new jupyter? notebook|add(ed)? jupyter? notebook/i'
dependencies:
    - '/dependencies|deps|requirements/i'
documentation:
    - '/docs|documentation/i'
